export const OBJECTIVE_TYPES = {
  skeleton: { hookName: "onSkeleton" },
  revive: { hookName: "onRevive" },
  coin: { hookName: "onCoin" },
  wagon: { hookName: "onWagonSpawn" },
  catapult: { hookName: "onCatapult" },
  chain: { hookName: "onChain" },
  loop: { hookName: "onLoop" },
  constellation: { hookName: "onConstellation" },
  apocalypse: { hookName: "onApocalypse" },
  geyser: { hookName: "onGeyser" },
  metronome: { hookName: "onMetronome" },
  magnetField: { hookName: "onMagnetField" },
  score: { hookName: "onScore" },
  portalUse: { hookName: "onPortalUse" },
  visitor: { hookName: "onVisitorBoard" },
};

// Layout helpers (concaténés pour réduire la duplication)
// Rails sur row 13 de col A à B (inclus)
function railRow(aCol, bCol, row = 13) {
  const parts = [];
  for (let c = aCol; c <= bCol; c++) parts.push(`${c}.${row}.R`);
  return parts.join(",");
}
function tile(c, r, code) { return `${c}.${r}.${code}`; }

export const LEVELS = [
  // MONDE 1 — Premiers pas (tuto doux, 1-1 à 1-5)
  {
    id: "1-1",
    world: 1,
    title: "Premier wagon",
    hint: "Appuie sur X pour lancer un wagon. Pose une LAVE 🔥 sur le rail pour le transformer.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "erase"],
    tileBudget: 3,
    wagonLimit: 2,
    objectives: [
      { id: "skel1", type: "skeleton", target: 1, label: "Transforme 1 wagon" },
    ],
    stars: { time: { under: 30 }, efficient: { tilesUnder: 1 } },
    timeLimit: 60,
    platinum: { label: "Premier squelette sous 12s", check: (r) => r.time < 12 },
  },
  {
    id: "1-2",
    world: 1,
    title: "Le sauveur",
    hint: "LAVE 🔥 puis EAU 💧 APRÈS. Le squelette traverse l'eau et redevient vivant.",
    layout: "v2:" + railRow(3, 16) + "," + tile(8, 12, "L"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["water", "erase"],
    tileBudget: 3,
    wagonLimit: 2,
    objectives: [
      { id: "rev1", type: "revive", target: 1, label: "Ressuscite 1 squelette" },
    ],
    stars: { time: { under: 35 }, efficient: { tilesUnder: 1 } },
    timeLimit: 70,
    platinum: { label: "Ressuscite 2 squelettes", check: (r) => r.revives >= 2 },
  },
  {
    id: "1-3",
    world: 1,
    title: "La collecte",
    hint: "Pose des PIÈCES 🪙 sur le chemin. Le wagon les ramasse en passant.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["coin", "erase"],
    tileBudget: 6,
    wagonLimit: 2,
    objectives: [
      { id: "coin5", type: "coin", target: 5, label: "Collecte 5 pièces" },
    ],
    stars: { time: { under: 30 }, efficient: { tilesUnder: 5 } },
    timeLimit: 60,
    platinum: { label: "Ramasse 6 pièces", check: (r) => r.coins >= 6 },
  },
  {
    id: "1-4",
    world: 1,
    title: "Catapulte",
    hint: "TRAMPOLINE 🎪 + VENTILATEUR 🌀 au-dessus = CATAPULTE. Le wagon s'envole.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["trampoline", "fan", "erase"],
    tileBudget: 4,
    wagonLimit: 2,
    objectives: [
      { id: "cata1", type: "catapult", target: 1, label: "Catapulte 1 wagon" },
    ],
    stars: { time: { under: 40 }, efficient: { tilesUnder: 2 } },
    timeLimit: 75,
    platinum: { label: "Catapulte 2 wagons d'affilée", check: (r) => r.catapults >= 2 },
  },
  {
    id: "1-5",
    world: 1,
    title: "La boucle",
    hint: "RAIL LOOP ⭕ sur le rail = 360° complet. Ajoute un BOOST ⚡ avant si besoin.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["rail_loop", "boost", "erase"],
    tileBudget: 3,
    wagonLimit: 2,
    objectives: [
      { id: "loop1", type: "loop", target: 1, label: "Complète 1 looping" },
    ],
    stars: { time: { under: 40 }, efficient: { tilesUnder: 1 } },
    timeLimit: 75,
    platinum: { label: "2 loopings d'affilée", check: (r) => r.loops >= 2 },
  },

  // MONDE 2 — Combos (2-1 à 2-10, 5⭐ pour débloquer)
  {
    id: "2-1",
    world: 2,
    title: "Triple incinération",
    hint: "3 squelettes avec 2 tuiles LAVE 🔥 max. Place-les bien.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "erase"],
    tileBudget: 2,
    wagonLimit: 3,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "Transforme 3 wagons" },
    ],
    stars: { time: { under: 50 }, efficient: { tilesUnder: 1 } },
    timeLimit: 90,
    platinum: { label: "5 squelettes avec 2 tuiles max", check: (r) => r.skeletons >= 5 && r.tiles <= 2 },
  },
  {
    id: "2-2",
    world: 2,
    title: "Cycle parfait",
    hint: "LAVE 🔥 puis EAU 💧 : 2 cycles complets avec 2 wagons.",
    layout: "v2:" + railRow(3, 16) + "," + tile(7, 12, "L"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["water", "lava", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "skel2", type: "skeleton", target: 2, label: "Transforme 2 wagons" },
      { id: "rev2", type: "revive", target: 2, label: "Ressuscite 2 squelettes" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 3 } },
    timeLimit: 90,
    platinum: { label: "Sans poser de LAVE supplémentaire", check: (r) => !r.tools.includes("lava") },
  },
  {
    id: "2-3",
    world: 2,
    title: "Chaîne d'or",
    hint: "3 PIÈCES 🪙 en diagonale déclenchent la CHAÎNE D'OR (combo).",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["coin", "erase"],
    tileBudget: 4,
    wagonLimit: 2,
    objectives: [
      { id: "coin3", type: "coin", target: 3, label: "Collecte 3 pièces (diagonale)" },
      { id: "score80", type: "score", target: 80, label: "Atteins 80 pts (multi chaîne)" },
    ],
    stars: { time: { under: 40 }, efficient: { tilesUnder: 3 } },
    timeLimit: 75,
    platinum: { label: "2 chaînes d'or dans la même run", check: (r) => r.chains >= 2 },
  },
  {
    id: "2-4",
    world: 2,
    title: "Acrobate",
    hint: "CATAPULTE (🎪+🌀 au-dessus) + LOOP ⭕ dans la même run.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["rail_loop", "trampoline", "fan", "boost", "erase"],
    tileBudget: 5,
    wagonLimit: 3,
    objectives: [
      { id: "cata1", type: "catapult", target: 1, label: "1 catapulte" },
      { id: "loop1", type: "loop", target: 1, label: "1 looping" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 3 } },
    timeLimit: 90,
    platinum: { label: "2 catapultes ET 2 loopings", check: (r) => r.catapults >= 2 && r.loops >= 2 },
  },
  {
    id: "2-5",
    world: 2,
    title: "Le Yin Yang",
    hint: "Alterne LAVE 🔥 et EAU 💧 : fais des squelettes ET ressuscite-les.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "water", "erase"],
    tileBudget: 4,
    wagonLimit: 4,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "Transforme 3 wagons" },
      { id: "rev3", type: "revive", target: 3, label: "Ressuscite 3 squelettes" },
    ],
    stars: { time: { under: 80 }, efficient: { tilesUnder: 3 } },
    timeLimit: 110,
    platinum: { label: "4 squelettes ET 4 ressuscités", check: (r) => r.skeletons >= 4 && r.revives >= 4 },
  },
  {
    id: "2-6",
    world: 2,
    title: "Escalier d'or",
    hint: "Les rails montants ↗ forment une rampe. Pose PIÈCES 🪙 dessus.",
    layout: "v2:" + railRow(3, 8) + "," + tile(9, 12, "U") + "," + tile(10, 11, "U") + "," + tile(11, 10, "U") + "," + tile(12, 9, "R") + "," + tile(13, 9, "R") + "," + tile(14, 9, "R") + "," + tile(15, 9, "R"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["coin", "boost", "erase"],
    tileBudget: 6,
    wagonLimit: 2,
    objectives: [
      { id: "coin8", type: "coin", target: 8, label: "Collecte 8 pièces" },
    ],
    stars: { time: { under: 45 }, efficient: { tilesUnder: 5 } },
    timeLimit: 75,
    platinum: { label: "10 pièces ramassées", check: (r) => r.coins >= 10 },
  },
  {
    id: "2-7",
    world: 2,
    title: "Le grand saut",
    hint: "3 catapultes. Les trampolines peuvent être réutilisés par les wagons.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["trampoline", "fan", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "cata3", type: "catapult", target: 3, label: "Catapulte 3 wagons" },
    ],
    stars: { time: { under: 55 }, efficient: { tilesUnder: 3 } },
    timeLimit: 90,
    platinum: { label: "5 catapultes dans la run", check: (r) => r.catapults >= 5 },
  },
  {
    id: "2-8",
    world: 2,
    title: "Looper pro",
    hint: "3 loopings différents dans la run. 1 RAIL LOOP ⭕ peut servir plusieurs wagons.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["rail_loop", "boost", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "loop3", type: "loop", target: 3, label: "Complète 3 loopings" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 2 } },
    timeLimit: 90,
    platinum: { label: "5 loopings avec 2 tuiles max", check: (r) => r.loops >= 5 && r.tiles <= 2 },
  },
  {
    id: "2-9",
    world: 2,
    title: "Lave et glace",
    hint: "3 GLACES 🧊 alignées = PATINOIRE. Combine avec LAVE 🔥.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "ice", "erase"],
    tileBudget: 6,
    wagonLimit: 3,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "Transforme 3 wagons" },
      { id: "score150", type: "score", target: 150, label: "Atteins 150 pts" },
    ],
    stars: { time: { under: 55 }, efficient: { tilesUnder: 5 } },
    timeLimit: 90,
    platinum: { label: "300 pts cumulés", check: (r) => r.score >= 300 },
  },
  {
    id: "2-10",
    world: 2,
    title: "APOCALYPSE !",
    hint: "5 transformations LAVE 🔥 en moins de 2.5s. Prépare plusieurs flaques.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "boost", "erase"],
    tileBudget: 5,
    wagonLimit: 5,
    objectives: [
      { id: "apo1", type: "apocalypse", target: 1, label: "Déclenche 1 APOCALYPSE" },
    ],
    stars: { time: { under: 50 }, efficient: { tilesUnder: 4 } },
    timeLimit: 90,
    platinum: { label: "APOCALYPSE sous 30s", check: (r) => r.apocalypses >= 1 && r.time < 30 },
  },

  // MONDE 3 — Challenges contraintes (3-1 à 3-10, 12⭐)
  {
    id: "3-1",
    world: 3,
    title: "Minimaliste",
    hint: "5 squelettes avec SEULEMENT 1 tuile. Une grosse flaque sert plusieurs wagons.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "erase"],
    tileBudget: 1,
    wagonLimit: 5,
    objectives: [
      { id: "skel5", type: "skeleton", target: 5, label: "5 squelettes" },
    ],
    stars: { time: { under: 45 }, efficient: { tilesUnder: 1 } },
    timeLimit: 75,
    platinum: { label: "8 squelettes avec 1 seule tuile", check: (r) => r.skeletons >= 8 },
  },
  {
    id: "3-2",
    world: 3,
    title: "Time trial",
    hint: "8 squelettes en 30 secondes ⏱. BOOST ⚡ accélère les wagons.",
    layout: "v2:" + railRow(3, 16) + "," + tile(8, 12, "L") + "," + tile(12, 12, "L"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "boost", "erase"],
    tileBudget: 4,
    wagonLimit: 4,
    objectives: [
      { id: "skel8", type: "skeleton", target: 8, label: "8 squelettes" },
    ],
    stars: { time: { under: 25 }, efficient: { tilesUnder: 3 } },
    timeLimit: 30,
    platinum: { label: "10 squelettes sous 20s", check: (r) => r.skeletons >= 10 && r.time < 20 },
  },
  {
    id: "3-3",
    world: 3,
    title: "Le magot",
    hint: "400 points. Pièces + squelettes + chaînes d'or = combo multi.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "water", "coin", "erase"],
    tileBudget: 8,
    wagonLimit: 3,
    objectives: [
      { id: "score400", type: "score", target: 400, label: "Atteins 400 pts" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 6 } },
    timeLimit: 90,
    platinum: { label: "800 pts cumulés", check: (r) => r.score >= 800 },
  },
  {
    id: "3-4",
    world: 3,
    title: "Portail maître",
    hint: "2 portails + 1 aimant à côté = VORTEX. Le wagon fait des allers-retours.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["portal", "magnet", "lava", "erase"],
    tileBudget: 6,
    wagonLimit: 2,
    objectives: [
      { id: "skel4", type: "skeleton", target: 4, label: "4 squelettes avec 2 wagons" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 5 } },
    timeLimit: 90,
    platinum: { label: "6 squelettes avec 2 wagons", check: (r) => r.skeletons >= 6 },
  },
  {
    id: "3-5",
    world: 3,
    title: "Double sommet",
    hint: "2 catapultes ET 2 loopings dans la même run.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["rail_loop", "trampoline", "fan", "boost", "erase"],
    tileBudget: 6,
    wagonLimit: 3,
    objectives: [
      { id: "cata2", type: "catapult", target: 2, label: "2 catapultes" },
      { id: "loop2", type: "loop", target: 2, label: "2 loopings" },
    ],
    stars: { time: { under: 75 }, efficient: { tilesUnder: 5 } },
    timeLimit: 110,
    platinum: { label: "3 catapultes ET 3 loopings", check: (r) => r.catapults >= 3 && r.loops >= 3 },
  },
  {
    id: "3-6",
    world: 3,
    title: "Vide-caisse",
    hint: "15 pièces en 45s. Les rails up/down permettent de couvrir la hauteur.",
    layout: "v2:" + railRow(3, 16) + "," + tile(8, 12, "U") + "," + tile(9, 11, "U") + "," + tile(10, 11, "R") + "," + tile(11, 11, "R") + "," + tile(12, 11, "D"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["coin", "boost", "erase"],
    tileBudget: 10,
    wagonLimit: 3,
    objectives: [
      { id: "coin15", type: "coin", target: 15, label: "15 pièces" },
    ],
    stars: { time: { under: 40 }, efficient: { tilesUnder: 8 } },
    timeLimit: 60,
    platinum: { label: "20 pièces sous 30s", check: (r) => r.coins >= 20 && r.time < 30 },
  },
  {
    id: "3-7",
    world: 3,
    title: "Patinoire mortelle",
    hint: "3 GLACES 🧊 alignées sur le rail = PATINOIRE. Le wagon glisse x1.6 vitesse. Place ta LAVE 🔥 en sortie.",
    // Glaces remplacent le rail sur cols 8-10 pour que le wagon glisse vraiment
    layout: "v2:" + railRow(3, 7) + "," + tile(8, 13, "I") + "," + tile(9, 13, "I") + "," + tile(10, 13, "I") + "," + railRow(11, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "erase"],
    tileBudget: 2,
    wagonLimit: 3,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 squelettes" },
    ],
    stars: { time: { under: 40 }, efficient: { tilesUnder: 1 } },
    timeLimit: 70,
    platinum: { label: "5 squelettes sur patinoire", check: (r) => r.skeletons >= 5 },
  },
  {
    id: "3-8",
    world: 3,
    title: "Le grand frisson",
    hint: "APOCALYPSE avec moins de 4 tuiles. Concentration + timing.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "boost", "erase"],
    tileBudget: 3,
    wagonLimit: 6,
    objectives: [
      { id: "apo1", type: "apocalypse", target: 1, label: "1 APOCALYPSE" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 2 } },
    timeLimit: 90,
    platinum: { label: "APOCALYPSE sans BOOST posé", check: (r) => r.apocalypses >= 1 && !r.tools.includes("boost") },
  },
  {
    id: "3-9",
    world: 3,
    title: "Géyser Express",
    hint: "EAU 💧 au-dessus d'un VENTILATEUR 🌀 = GEYSER. 2 geysers pour réussir.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["water", "fan", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "rev2", type: "revive", target: 2, label: "2 ressuscitations via geyser" },
    ],
    stars: { time: { under: 45 }, efficient: { tilesUnder: 3 } },
    timeLimit: 75,
    platinum: { label: "4 geysers déclenchés", check: (r) => r.geysers >= 4 },
  },
  {
    id: "3-10",
    world: 3,
    title: "Maître forain",
    hint: "800 pts avec tous les outils. Combos multiplient. Temps serré.",
    layout: "v2:" + railRow(3, 16) + "," + tile(10, 12, "L"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "water", "coin", "boost", "rail_loop", "trampoline", "fan", "portal", "erase"],
    tileBudget: 10,
    wagonLimit: 4,
    objectives: [
      { id: "score800", type: "score", target: 800, label: "Atteins 800 pts" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 7 } },
    timeLimit: 90,
    platinum: { label: "1500 pts cumulés", check: (r) => r.score >= 1500 },
  },

  // MONDE 4 — Experts (4-1 à 4-5, 20⭐)
  {
    id: "4-1",
    world: 4,
    title: "Symphonie",
    hint: "Enchaîne 4 combos DIFFÉRENTS : catapulte, loop, chaîne d'or, apocalypse.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "coin", "rail_loop", "trampoline", "fan", "boost", "erase"],
    tileBudget: 10,
    wagonLimit: 6,
    objectives: [
      { id: "cata1", type: "catapult", target: 1, label: "1 catapulte" },
      { id: "loop1", type: "loop", target: 1, label: "1 looping" },
      { id: "apo1", type: "apocalypse", target: 1, label: "1 APOCALYPSE" },
      { id: "coin5", type: "coin", target: 5, label: "5 pièces" },
    ],
    stars: { time: { under: 90 }, efficient: { tilesUnder: 7 } },
    timeLimit: 120,
    platinum: { label: "+ 2 chaînes d'or en bonus", check: (r) => r.chains >= 2 },
  },
  {
    id: "4-2",
    world: 4,
    title: "Ultra minimaliste",
    hint: "10 squelettes avec 1 SEULE tuile LAVE 🔥. Tu as 12 wagons à balancer.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "erase"],
    tileBudget: 1,
    wagonLimit: 12,
    objectives: [
      { id: "skel10", type: "skeleton", target: 10, label: "10 squelettes" },
    ],
    stars: { time: { under: 80 }, efficient: { tilesUnder: 1 } },
    timeLimit: 120,
    platinum: { label: "15 squelettes avec 1 tuile", check: (r) => r.skeletons >= 15 },
  },
  {
    id: "4-3",
    world: 4,
    title: "Boucle infinie",
    hint: "Le portail GAUCHE te renvoie direct à droite = fin de run. Construis une RAMPE ↗↘ pour passer AU-DESSUS, puis le portail droit te téléporte en boucle à gauche.",
    // Rails 3-4, portal A (5,13), rails 6-12, portal B (13,13), rails 14-16
    // Le wagon entre portail A par défaut → ressort portail B → fin. Il faut bypass A via ramp.
    layout: "v2:" + railRow(3, 4) + "," + tile(5, 13, "P") + "," + railRow(6, 12) + "," + tile(13, 13, "P") + "," + railRow(14, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["rail_up", "rail_down", "rail", "lava", "coin", "boost", "erase"],
    tileBudget: 10,
    wagonLimit: 2,
    objectives: [
      { id: "skel5", type: "skeleton", target: 5, label: "5 squelettes (boucle les wagons)" },
      { id: "coin8", type: "coin", target: 8, label: "8 pièces" },
    ],
    stars: { time: { under: 90 }, efficient: { tilesUnder: 8 } },
    timeLimit: 130,
    platinum: { label: "10 squelettes avant 90s", check: (r) => r.skeletons >= 10 && r.time < 90 },
  },
  {
    id: "4-4",
    world: 4,
    title: "Le gardien",
    hint: "1500 pts. Tous les outils. Pont fragile pré-placé : attention.",
    layout: "v2:" + railRow(3, 7) + "," + tile(8, 13, "N") + "," + tile(9, 13, "N") + "," + railRow(10, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "water", "coin", "boost", "rail_loop", "trampoline", "fan", "portal", "magnet", "ice", "bridge", "erase"],
    tileBudget: 14,
    wagonLimit: 6,
    objectives: [
      { id: "score1500", type: "score", target: 1500, label: "Atteins 1500 pts" },
    ],
    stars: { time: { under: 90 }, efficient: { tilesUnder: 10 } },
    timeLimit: 130,
    platinum: { label: "3000 pts cumulés", check: (r) => r.score >= 3000 },
  },
  {
    id: "4-5",
    world: 4,
    title: "Maître absolu",
    hint: "3 APOCALYPSES dans la run. Il te faudra 15 wagons et des flaques bien placées.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "water", "boost", "erase"],
    tileBudget: 8,
    wagonLimit: 15,
    objectives: [
      { id: "apo3", type: "apocalypse", target: 3, label: "3 APOCALYPSES" },
    ],
    stars: { time: { under: 120 }, efficient: { tilesUnder: 6 } },
    timeLimit: 150,
    platinum: { label: "5 APOCALYPSES dans la même run", check: (r) => r.apocalypses >= 5 },
  },

  // MONDE 5 — ÉNIGMES (5-1 à 5-8, 28⭐ pour débloquer)
  // Ici le BUT est clair mais la SOLUTION pas dite. Le joueur expérimente.
  {
    id: "5-1",
    world: 5,
    title: "Les cimes",
    hint: "Collecte les pièces en hauteur. Catapulte = trampoline 🎪 + ventilateur 🌀 juste au-dessus. Le wagon s'envole en parabole.",
    // 3 pièces à row 10 (accessible au sommet d'un catapulte)
    // Trampoline doit être placé ~col 5-6 pour que l'arc parabolique passe par 7/10/13
    layout: "v2:" + railRow(3, 16) + "," + tile(8, 10, "C") + "," + tile(11, 10, "C") + "," + tile(14, 10, "C"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["trampoline", "fan", "boost", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "coin3", type: "coin", target: 3, label: "Collecte les 3 pièces en hauteur" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 3 } },
    timeLimit: 100,
    platinum: { label: "Sans poser de BOOST", check: (r) => !r.tools.includes("boost") },
  },
  {
    id: "5-2",
    world: 5,
    title: "L'abîme",
    hint: "Un trou coupe ton parc en deux. Fais 3 squelettes quand même.",
    // Rails coupés au milieu (gap cols 8-11)
    layout: "v2:" + railRow(3, 7) + "," + railRow(12, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "portal", "bridge", "erase"],
    tileBudget: 5,
    wagonLimit: 3,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 squelettes de l'autre côté" },
    ],
    stars: { time: { under: 75 }, efficient: { tilesUnder: 4 } },
    timeLimit: 110,
    platinum: { label: "5 squelettes malgré l'abîme", check: (r) => r.skeletons >= 5 },
  },
  {
    id: "5-3",
    world: 5,
    title: "Le vortex",
    hint: "5 squelettes avec seulement 2 wagons. Fais-les repasser.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["portal", "magnet", "lava", "erase"],
    tileBudget: 5,
    wagonLimit: 2,
    objectives: [
      { id: "skel5", type: "skeleton", target: 5, label: "5 squelettes (2 wagons !)" },
    ],
    stars: { time: { under: 90 }, efficient: { tilesUnder: 4 } },
    timeLimit: 130,
    platinum: { label: "8 squelettes avec 2 wagons", check: (r) => r.skeletons >= 8 },
  },
  {
    id: "5-4",
    world: 5,
    title: "Le pont suspendu",
    hint: "Le pont fragile 🌉 casse après 2 passages. Collecte 5 pièces en suspens au-dessus.",
    // Pont fragile pré-placé au milieu, pièces en hauteur autour
    layout: "v2:" + railRow(3, 7) + "," + tile(8, 13, "N") + "," + tile(9, 13, "N") + "," + tile(10, 13, "N") + "," + railRow(11, 16) + "," + tile(7, 11, "C") + "," + tile(9, 11, "C") + "," + tile(11, 11, "C") + "," + tile(13, 11, "C") + "," + tile(5, 11, "C"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["trampoline", "fan", "boost", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "coin5", type: "coin", target: 5, label: "5 pièces en suspens" },
    ],
    stars: { time: { under: 70 }, efficient: { tilesUnder: 3 } },
    timeLimit: 100,
    platinum: { label: "5 pièces sous 45s", check: (r) => r.coins >= 5 && r.time < 45 },
  },
  {
    id: "5-5",
    world: 5,
    title: "Le plongeur",
    hint: "Le wagon doit SAUTER PAR-DESSUS la lave SANS SE TRANSFORMER. Si un wagon devient squelette : c'est perdu !",
    // Lave pré-placée large, pièces au sol après
    layout: "v2:" + railRow(3, 7) + "," + tile(8, 13, "L") + "," + tile(9, 13, "L") + "," + tile(10, 13, "L") + "," + railRow(11, 16) + "," + tile(12, 13, "C") + "," + tile(13, 13, "C") + "," + tile(14, 13, "C") + "," + tile(15, 13, "C") + "," + tile(16, 13, "C"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["trampoline", "fan", "boost", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    failOn: { skeleton: 1 },
    objectives: [
      { id: "coin5", type: "coin", target: 5, label: "5 pièces de l'autre côté" },
    ],
    stars: { time: { under: 70 }, efficient: { tilesUnder: 3 } },
    timeLimit: 100,
    platinum: { label: "5 pièces sous 40s", check: (r) => r.coins >= 5 && r.time < 40 },
  },
  {
    id: "5-6",
    world: 5,
    title: "Patinoire infernale",
    hint: "Les 3 GLACES 🧊 en ligne font GLISSER le wagon (x1.6 vitesse). Fais 3 squelettes.",
    // Glaces AU MILIEU des rails (row 13 = remplacent rails) → wagons glissent dessus
    layout: "v2:" + railRow(3, 7) + "," + tile(8, 13, "I") + "," + tile(9, 13, "I") + "," + tile(10, 13, "I") + "," + railRow(11, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "boost", "trampoline", "fan", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 squelettes" },
    ],
    stars: { time: { under: 55 }, efficient: { tilesUnder: 3 } },
    timeLimit: 90,
    platinum: { label: "5 squelettes sous 30s", check: (r) => r.skeletons >= 5 && r.time < 30 },
  },
  {
    id: "5-7",
    world: 5,
    title: "Énigme du forain",
    hint: "La grande roue 🎡 est déjà là. Encaisse 300 points grâce à elle.",
    // Wheel placée au centre — produit coins/VIP auto
    layout: "v2:" + railRow(3, 16) + "," + tile(9, 10, "Y"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["rail_loop", "coin", "boost", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "score300", type: "score", target: 300, label: "Encaisse 300 pts" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 3 } },
    timeLimit: 110,
    platinum: { label: "600 pts via la roue", check: (r) => r.score >= 600 },
  },
  {
    id: "5-8",
    world: 5,
    title: "La dernière énigme",
    hint: "2 wagons. 8 squelettes. Tous les outils. Démerde-toi.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "water", "portal", "magnet", "trampoline", "fan", "boost", "rail_loop", "ice", "erase"],
    tileBudget: 8,
    wagonLimit: 2,
    objectives: [
      { id: "skel8", type: "skeleton", target: 8, label: "8 squelettes avec 2 wagons" },
    ],
    stars: { time: { under: 120 }, efficient: { tilesUnder: 6 } },
    timeLimit: 180,
    platinum: { label: "12 squelettes avec 2 wagons", check: (r) => r.skeletons >= 12 },
  },

  // MONDE 6 — Mécaniques secrètes (6-1 à 6-5, 35⭐ pour débloquer)
  {
    id: "6-1",
    world: 6,
    title: "Le pont chancelant",
    hint: "Le PONT FRAGILE 🌉 col 8 casse après 2 passages. Transforme 3 wagons malgré la casse.",
    layout: "v2:" + railRow(3, 7) + "," + tile(8, 13, "N") + "," + railRow(9, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "erase"],
    tileBudget: 3,
    wagonLimit: 4,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 squelettes (gère la casse du pont)" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 2 } },
    timeLimit: 100,
    platinum: { label: "5 squelettes malgré la casse", check: (r) => r.skeletons >= 5 },
  },
  {
    id: "6-2",
    world: 6,
    title: "Tunnel maléfique",
    hint: "Le TUNNEL HANTÉ 🏚 col 10 transforme les passagers qui le traversent. Pas besoin de lave.",
    layout: "v2:" + railRow(3, 16) + "," + tile(10, 13, "X"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "erase"],
    tileBudget: 2,
    wagonLimit: 3,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 squelettes (le tunnel fait le travail)" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 0 } },
    timeLimit: 100,
    platinum: { label: "5 squelettes sans poser de tuile", check: (r) => r.skeletons >= 5 && r.tiles === 0 },
  },
  {
    id: "6-3",
    world: 6,
    title: "Cascade fatale",
    hint: "Pose 3 EAUX 💧 verticales col 8 au-dessus de la lave : CASCADE 🌊 = pont temporaire 8s. Traverse sans brûler.",
    layout: "v2:" + railRow(3, 7) + "," + tile(8, 13, "L") + "," + railRow(9, 16) + "," + tile(11, 13, "C") + "," + tile(13, 13, "C") + "," + tile(15, 13, "C"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["water", "erase"],
    tileBudget: 4,
    wagonLimit: 2,
    failOn: { skeleton: 1 },
    objectives: [
      { id: "coin3", type: "coin", target: 3, label: "Ramasse 3 pièces après le pont cascade" },
    ],
    stars: { time: { under: 70 }, efficient: { tilesUnder: 3 } },
    timeLimit: 120,
    platinum: { label: "3 pièces sous 50s", check: (r) => r.coins >= 3 && r.time < 50 },
  },
  {
    id: "6-4",
    world: 6,
    title: "Yin Yang infini",
    hint: "PORTAIL 🌀 + AIMANT 🧲 adjacent = VORTEX qui attire les wagons. Alterne LAVE/EAU pour re-transformer en boucle.",
    layout: "v2:" + railRow(3, 16) + "," + tile(13, 13, "P") + "," + tile(14, 13, "M"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["lava", "water", "erase"],
    tileBudget: 5,
    wagonLimit: 1,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 transformations avec 1 seul wagon" },
    ],
    stars: { time: { under: 90 }, efficient: { tilesUnder: 3 } },
    timeLimit: 150,
    platinum: { label: "5 transformations avec 1 wagon", check: (r) => r.skeletons >= 5 },
  },
  {
    id: "6-5",
    world: 6,
    title: "Métronome infernal",
    hint: "2 BOOSTS ⚡ verticaux col 10 avec LAVE entre = MÉTRONOME. Catapulte un wagon : top→bottom <0.8s multiplie x2.",
    layout: "v2:" + railRow(3, 16) + "," + tile(10, 9, "B") + "," + tile(10, 11, "L") + "," + tile(10, 13, "B"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["trampoline", "fan", "boost", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "metro1", type: "metronome", target: 1, label: "Déclenche 1 MÉTRONOME" },
    ],
    stars: { time: { under: 90 }, efficient: { tilesUnder: 3 } },
    timeLimit: 130,
    platinum: { label: "3 métronomes déclenchés", check: (r) => r.metronomes >= 3 },
  },
  {
    id: "6-6",
    world: 6,
    title: "Ramassage",
    hint: "3 visiteurs 🧍 attendent sur le rail. Lance des wagons qui les embarquent en passant (max 4 passagers/wagon).",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["boost", "erase"],
    visitors: [
      { col: 8, row: 13 },
      { col: 11, row: 13 },
      { col: 14, row: 13 },
    ],
    tileBudget: 3,
    wagonLimit: 3,
    objectives: [
      { id: "vis3", type: "visitor", target: 3, label: "Embarque 3 visiteurs" },
    ],
    stars: { time: { under: 45 }, efficient: { tilesUnder: 2 } },
    timeLimit: 90,
    platinum: { label: "3 visiteurs en 1 seul wagon", check: (r) => r.visitors >= 3 && r.wagons <= 1 },
  },
  {
    id: "6-7",
    world: 6,
    title: "Champ de mines",
    hint: "3 BOMBES 💣 pré-placées row 12 explosent au passage du wagon (bombe + 4 voisines → lave). Fais 3 squelettes.",
    layout: "v2:" + railRow(3, 16) + "," + tile(7, 12, "E") + "," + tile(11, 12, "E") + "," + tile(14, 12, "E"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["boost", "erase"],
    tileBudget: 2,
    wagonLimit: 4,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 squelettes (les bombes font le travail)" },
    ],
    stars: { time: { under: 45 }, efficient: { tilesUnder: 1 } },
    timeLimit: 90,
    platinum: { label: "5 squelettes sans poser de tuile", check: (r) => r.skeletons >= 5 && r.tiles === 0 },
  },
  {
    id: "6-8",
    world: 6,
    title: "Alarme !",
    hint: "ALARME 💧 pré-placée : dans 10s les LAVES deviennent eau 5s. Attends la vague, traverse, ramasse 3 pièces.",
    layout: "v2:" + railRow(3, 16)
      + "," + tile(10, 13, "L") + "," + tile(11, 13, "L") + "," + tile(12, 13, "L")
      + "," + tile(13, 13, "C") + "," + tile(14, 13, "C") + "," + tile(15, 13, "C")
      + "," + tile(10, 11, "A"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["boost", "erase"],
    tileBudget: 2,
    wagonLimit: 3,
    failOn: { skeleton: 1 },
    objectives: [
      { id: "coin3", type: "coin", target: 3, label: "3 pièces sans brûler de wagon" },
    ],
    stars: { time: { under: 30 }, efficient: { tilesUnder: 1 } },
    timeLimit: 60,
    platinum: { label: "3 pièces avec 0 boost posé", check: (r) => r.coins >= 3 && !r.tools.includes("boost") },
  },

  // MONDE 7 — Contrats VIP (7-1 à 7-5, 45⭐ pour débloquer)
  {
    id: "7-1",
    world: 7,
    title: "VIP transport",
    hint: "2 VIP attendent. Amène-les à destination SANS qu'aucun visiteur ne soit brûlé. Lave interdite.",
    layout: "v2:" + railRow(3, 16),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["boost", "coin", "erase"],
    visitors: [
      { col: 8, row: 13, isVIP: true },
      { col: 13, row: 13, isVIP: true },
    ],
    tileBudget: 5,
    wagonLimit: 3,
    failOn: { skeleton: 1 },
    objectives: [
      { id: "vis2", type: "visitor", target: 2, label: "Embarque les 2 VIP" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 3 } },
    timeLimit: 100,
    platinum: { label: "2 VIP sans poser de BOOST", check: (r) => r.visitors >= 2 && !r.tools.includes("boost") },
  },
  {
    id: "7-2",
    world: 7,
    title: "Cascade explosive",
    hint: "6 BOMBES 💣 adjacentes : une explosion déclenche ses voisines en chaîne (+0.15s). Décroche une APOCALYPSE.",
    layout: "v2:" + railRow(3, 16)
      + "," + tile(8, 12, "E") + "," + tile(9, 12, "E") + "," + tile(10, 12, "E")
      + "," + tile(12, 12, "E") + "," + tile(13, 12, "E") + "," + tile(14, 12, "E"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["boost", "erase"],
    tileBudget: 2,
    wagonLimit: 6,
    objectives: [
      { id: "apo1", type: "apocalypse", target: 1, label: "Déclenche 1 APOCALYPSE via cascade" },
    ],
    stars: { time: { under: 60 }, efficient: { tilesUnder: 1 } },
    timeLimit: 100,
    platinum: { label: "APOCALYPSE sous 30s", check: (r) => r.apocalypses >= 1 && r.time < 30 },
  },
  {
    id: "7-3",
    world: 7,
    title: "Compte à rebours",
    hint: "ALARME ❄ dans 10s : tous les wagons gelés 3s. Fais 3 squelettes AVANT le gel (ou après, plus dur).",
    layout: "v2:" + railRow(3, 16)
      + "," + tile(7, 13, "L") + "," + tile(11, 13, "L")
      + "," + tile(8, 11, "G"),
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["boost", "erase"],
    tileBudget: 1,
    wagonLimit: 4,
    objectives: [
      { id: "skel3", type: "skeleton", target: 3, label: "3 squelettes (avant ou après le gel)" },
    ],
    stars: { time: { under: 25 }, efficient: { tilesUnder: 1 } },
    timeLimit: 45,
    platinum: { label: "3 squelettes avant le gel (<10s)", check: (r) => r.skeletons >= 3 && r.time < 10 },
  },

  // 7-4 : Le Labyrinthe — circuit multi-étages avec murailles lave
  {
    id: "7-4",
    world: 7,
    title: "Labyrinthe",
    hint: "Un dédale de rails et de laves. Suis la route jusqu'au TUNNEL HANTÉ en sortie. 4 pièces égarées à ramasser, puis 1 squelette final.",
    layout: "v2:"
      + "3.13.R,4.13.R,5.13.R,6.12.U,7.12.R,8.11.U,9.11.R,10.11.R,11.11.R,12.12.D,13.12.R,14.13.D,15.13.R,16.13.X"
      + ",6.11.L,6.10.L,10.10.L,10.9.L,14.12.L,14.11.L"
      + ",7.10.C,10.8.C,12.10.C,15.10.C",
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["water", "boost", "fan", "trampoline", "erase"],
    tileBudget: 4,
    wagonLimit: 3,
    objectives: [
      { id: "coin4", type: "coin", target: 4, label: "Ramasse les 4 pièces égarées" },
      { id: "skel1", type: "skeleton", target: 1, label: "1 wagon dans le tunnel de sortie" },
    ],
    stars: { time: { under: 90 }, efficient: { tilesUnder: 3 } },
    timeLimit: 120,
    platinum: { label: "Labyrinthe terminé sous 60s", check: (r) => r.time < 60 },
  },

  // 7-5 : Dédale final — failOn skeleton, visiteur VIP à embarquer
  {
    id: "7-5",
    world: 7,
    title: "Dédale final",
    hint: "Laisse le VIP embarquer et atteins la sortie SANS qu'aucun wagon ne brûle. Les bombes peuvent aider — ou tuer ta run.",
    layout: "v2:"
      + "3.13.R,4.13.R,5.13.P,6.13.R,7.12.U,8.12.R,9.12.R,10.12.R,11.12.R,12.13.D,13.13.R,14.13.P,15.13.R,16.13.R"
      + ",7.12.L,7.11.L,7.10.L,12.12.L,12.11.L,12.10.L"
      + ",9.13.E,10.13.E"
      + ",11.10.C,13.10.C"
      + ",16.13.X",
    playerSpawn: { col: 4, row: 13 },
    allowedTools: ["water", "bridge", "boost", "erase"],
    visitors: [
      { col: 10, row: 12, isVIP: true },
    ],
    tileBudget: 3,
    wagonLimit: 3,
    failOn: { skeleton: 1 },
    objectives: [
      { id: "vip1", type: "visitor", target: 1, label: "Embarque le VIP" },
      { id: "coin2", type: "coin", target: 2, label: "Ramasse 2 pièces" },
    ],
    stars: { time: { under: 120 }, efficient: { tilesUnder: 2 } },
    timeLimit: 150,
    platinum: { label: "VIP livré et moins de 2 tuiles posées", check: (r) => r.visitors >= 1 && r.tiles <= 1 },
  },
];

export function findLevel(id) {
  return LEVELS.find((l) => l.id === id) || null;
}

export function nextLevelId(id) {
  const i = LEVELS.findIndex((l) => l.id === id);
  if (i === -1 || i === LEVELS.length - 1) return null;
  return LEVELS[i + 1].id;
}

export function levelsByWorld() {
  const grouped = new Map();
  for (const lvl of LEVELS) {
    if (!grouped.has(lvl.world)) grouped.set(lvl.world, []);
    grouped.get(lvl.world).push(lvl);
  }
  return grouped;
}
